language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo cmake --version

install:
  # Install latest cmake
  - if [ $TRAVIS_OS_NAME == linux  ]; then
       sudo apt-get remove cmake
    && sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    && sudo apt-get update
    && sudo apt-get install cmake
    && sudo apt-get install mpich; fi
  - if [ $TRAVIS_OS_NAME == osx  ]; then
       brew update
    && brew unlink cmake
    && brew install cmake
    && brew unlink mpich
    && brew unlink open-mpi
    && brew install mpich; fi

script: ./configure -DCMAKE_BUILD_TYPE=debug && make

os:
  - linux
  - osx
