language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - echo cmake --version
  - if [ $TRAVIS_OS_NAME == linux  ]; then
         wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-i386.tar.gz
      && tar -xzf cmake-3.2.2-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.2.2-Linux-i386/* /usr; fi
  - if [ $TRAVIS_OS_NAME == osx  ]; then
         brew update
      && brew unlink cmake
      && brew install cmake; fi

script: ./configure -DCMAKE_BUILD_TYPE=debug && make

branches:
  only:
    - master

os:
  - linux
  - osx
